In [ ]:
import  numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.shape

(150, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop('species',axis=1)
y=df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
model_KNN=KNeighborsClassifier()

In [ ]:
model_KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
model_KNN.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm=SVC( gamma='auto')

In [ ]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

Grid Search CV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5, return_train_score=False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00474401, 0.00525532, 0.00597296, 0.00425906, 0.0053441 ,
        0.00429568, 0.00601468, 0.00378575]),
 'std_fit_time': array([0.00116083, 0.00232278, 0.00242021, 0.00173875, 0.0018738 ,
        0.00177816, 0.00270167, 0.00148629]),
 'mean_score_time': array([0.00305161, 0.00314097, 0.00378652, 0.00355678, 0.00378103,
        0.00295272, 0.00423832, 0.00228124]),
 'std_score_time': array([0.00061274, 0.00084945, 0.00121172, 0.00174718, 0.00172176,
        0.00050934, 0.0018026 , 0.00017959]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004744,0.001161,0.003052,0.000613,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005255,0.002323,0.003141,0.000849,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005973,0.002420,0.003787,0.001212,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004259,0.001739,0.003557,0.001747,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005344,0.001874,0.003781,0.001722,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004296,0.001778,0.002953,0.000509,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.006015,0.002702,0.004238,0.001803,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003786,0.001486,0.002281,0.000180,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C',	'param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
classifier2=GridSearchCV((model_KNN),{
    'n_neighbors':[1,3,5,7,9],
    'weights':['uniform','distance'],
    "algorithm":['auto'],
    "p":[1,2]
},cv=5, return_train_score=False)

In [ ]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'], 'n_neighbors': [1, 3, 5, 7, 9],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [ ]:
results=pd.DataFrame(classifier2.cv_results_)

In [ ]:
results.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_algorithm', 'param_n_neighbors', 'param_p', 'param_weights',
       'params', 'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [ ]:
results[['params',	'mean_test_score']]

                                               params  mean_test_score
0   {'algorithm': 'auto', 'n_neighbors': 1, 'p': 1...         0.960000
1   {'algorithm': 'auto', 'n_neighbors': 1, 'p': 1...         0.960000
2   {'algorithm': 'auto', 'n_neighbors': 1, 'p': 2...         0.960000
3   {'algorithm': 'auto', 'n_neighbors': 1, 'p': 2...         0.960000
4   {'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...         0.960000
5   {'algorithm': 'auto', 'n_neighbors': 3, 'p': 1...         0.960000
6   {'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...         0.966667
7   {'algorithm': 'auto', 'n_neighbors': 3, 'p': 2...         0.966667
8   {'algorithm': 'auto', 'n_neighbors': 5, 'p': 1...         0.960000
9   {'algorithm': 'auto', 'n_neighbors': 5, 'p': 1...         0.960000
10  {'algorithm': 'auto', 'n_neighbors': 5, 'p': 2...         0.973333
11  {'algorithm': 'auto', 'n_neighbors': 5, 'p': 2...         0.966667
12  {'algorithm': 'auto', 'n_neighbors': 7, 'p': 1...         0.973333
13  {'algorithm': 'auto', 'n_neighbors': 7, 'p': 1...         0.960000
14  {'algorithm': 'auto', 'n_neighbors': 7, 'p': 2...         0.980000
15  {'algorithm': 'auto', 'n_neighbors': 7, 'p': 2...         0.980000
16  {'algorithm': 'auto', 'n_neighbors': 9, 'p': 1...         0.973333
17  {'algorithm': 'auto', 'n_neighbors': 9, 'p': 1...         0.960000
18  {'algorithm': 'auto', 'n_neighbors': 9, 'p': 2...         0.973333
19  {'algorithm': 'auto', 'n_neighbors': 9, 'p': 2...         0.973333

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=4, cv=5, return_train_score=False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results=pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results[['params',	'mean_test_score']]

                          params  mean_test_score
0  {'kernel': 'linear', 'C': 10}         0.973333
1      {'kernel': 'rbf', 'C': 1}         0.980000
2     {'kernel': 'rbf', 'C': 20}         0.966667
3  {'kernel': 'linear', 'C': 20}         0.966667